Card layout add
fe-feb23-The-First-Attempt-Approve/react_phone-catalog pull request #7
Opened 2023-06-09 07:30 UTC by glots-a

2023-06-09 10:01 UTC, PashaMalyshkin requested changes

2023-06-09 10:01 UTC, PashaMalyshkin commented on src/components/Card/Card.tsx
> +            </p>
I'd rather create a separate component for it as-well. RroductCardParams for example

2023-06-09 10:04 UTC, PashaMalyshkin commented on src/components/Card/Card.tsx
> +            </p>
Also, I think ProductCard will be a better name than just Card for folder

2023-06-09 10:46 UTC, Esteban4769 commented on src/components/Card/Card.tsx
> +            </a>
This elements probably should be `button`, istead of `a`, since its not work like a link

2023-06-09 10:55 UTC, glots-a commented on src/components/Card/Card.tsx
> +          </div>
If logig will require it of cours, i will do it, but now  it may stay like it is!

2023-06-10 07:48 UTC, PashaMalyshkin approved these changes

2023-06-10 07:48 UTC, merged